#!/usr/bin/python3

from web3 import Web3
import os
import sys

rpcurl = os.environ['ETH_RPC_URL'] if "ETH_RPC_URL" in os.environ else "http://localhost:8545"
w3 = Web3(Web3.HTTPProvider(rpcurl))

try:
	command = sys.argv[1]
except:
	print("Missing command")
	sys.exit(1)

if command == "annoying":
	print("Puta Madre")
else:
	print("Error: unrecognized command " + sys.argv[1])

